### PR TITLE
Better tcp_closed error message

### LINKED ISSUE #6: Improve error message we can't connect to the database
Today, if you pass bad credentials when starting the connection to the database, it fails with a case clause error on :tcp_closed. We should instead handle this case and return a proper error, saying we were unable to connect to the database.

### PR DESCRIPTION
**Pull request by jquadrin**
closes #6

### CODE REVIEW

File: lib/mariaex/connection.ex [hunk 1]
```diff
@@ -187,6 +187,9 @@ defmodule Mariaex.Connection do
     end
   end
 
+  def handle_info({:tcp_closed, _}, s) do
+    raise %Mariaex.Error{message: "Unable to connect to database"}
+  end
```
Comment (ericmj) [inline lib/mariaex/connection.ex]: If we should match Postgrex the function should return `{:stop, %Mariaex.Error{message: "connection closed"}, s}`.
